MODEL:
  TYPE: swin_ode
  NAME: swin_ode_rk2_ema_lb_patch4_window7_224.yaml
  DROP_PATH_RATE: 0.5
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7
  SWINODE:
    RK_STEP: 2
    LEARNABLE_TYPE : 'ema' # ['gated', 'ema', 'standard']
TRAIN:
  BASE_LR: 5e-4
  WARMUP_EPOCHS: 20
